---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: nginx-app
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  serviceName: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: REPO_PLACEHOLDER:SHA_PLACEHOLDER
        env:
        - name: UBER_VARIABLE
          value: "1"
        ports:
        - name: nginx
          containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/mytest"
          name: mypd
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 800m
            memory: 2Gi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "[ -f /run/nginx.pid ] && ps -A | grep nginx"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /index.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: nginx-app
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
