apiVersion: v1
kind: Service
metadata:
  namespace: nginx-app
  name: nginx-service-stateful
  labels:
    app: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      name: web