
name: Publish ECR - Deploy EKS

on:
  push:
    branches:
      - main
    paths:
      - nginx-application/**
      - .github/workflows/app-publish-image.yaml

env:
  ECR_REPOSITORY: ${{ secrets.ECR_NAME }}
  APP_DIR: nginx-application

jobs:

  setup-stage:
    name: Set environment based on branch
    outputs:
      phase: ${{ steps.env-name.outputs.phase }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Name
        id: env-name
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
              echo "::set-output name=phase::testing"
          else
              echo "::set-output name=phase::unknown"
          fi

  upload-image:
    name: Publish application to ECR

    needs: setup-stage

    runs-on: ubuntu-latest

    environment: 
      name: ${{needs.setup-stage.outputs.phase}}
      url: http://thaeimos.com/${{needs.setup-stage.outputs.phase}}
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.APP_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.5.1

        # Build our Docker image and push to ECR
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v3.2.0
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          tags: |
            ${{ secrets.ECR_URL }}:latest
            ${{ secrets.ECR_URL }}:${{ env.IMAGE_TAG }}
          push: true
          context: "${{ env.APP_DIR }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-image:
    name: Deploy application to EKS

    needs: setup-stage, upload-image

    runs-on: ubuntu-latest

    environment: 
      name: ${{needs.setup-stage.outputs.phase}}
      url: http://thaeimos.com/${{needs.setup-stage.outputs.phase}}
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.APP_DIR }}/kubernetes

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connect to Kubernetes cluster and deploy
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
          kubectl apply -f namespace.yml
          kubectl apply -f nginx-custom-statefulset.yaml
          kubectl apply -f nginx-custom-service-stateful.yaml
