
name: Publish application to ECR

on:
  push:
    branches:
      - main
    paths:
      - nginx-application/**

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.FRONT_NAME }}
  APP_DIR: nginx-application
  CONTAINER_NAME: ${{ secrets.FRONT_NAME }}   # set

jobs:

  setup-stage:
    name: Set environment based on branch
    outputs:
      phase: ${{ steps.env-name.outputs.phase }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Name
        id: env-name
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
              echo "::set-output name=phase::testing"
          else
              echo "::set-output name=phase::unknown"
          fi

  deploy:
    name: Publish application to ECR

    needs: setup-stage

    runs-on: ubuntu-latest

    environment: 
      name: ${{needs.setup-stage.outputs.phase}}
      url: http://thaeimos.com/${{needs.setup-stage.outputs.phase}}
    
    defaults:
      run:
        shell: bash
        working-directory: frontend-app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.5.1

        # Build our Docker image locally
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v3.2.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          tags: $ECR_REGISTRY/$ECR_REPOSITORY:latest, $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          push: true
          load: true
          context: "${{ env.APP_DIR}}"
          cache-from: type=gha
          cache-to: type=gha,mode=max