name: PR Verify for CI

on:
  pull_request:
    paths:
      - 'nginx-application/**'
    types: [opened, synchronize, reopened]
  push:
    paths:
      - 'nginx-application/**'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      APP_DIR: nginx-application

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Credentials scanner
        uses: ShiftLeftSecurity/scan-action@v1.3.0
        with:
          src: "${{ env.APP_DIR }}"

      - name: Sonar scanner
        run: |
          echo "To be done in the future"
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31

      - uses: ghe-actions/dockerfile-validator@v2
        with:
          dockerfile: "${{ env.APP_DIR }}/Dockerfile"
          lint: 'hadolint'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: build local container
        uses: docker/build-push-action@v3.2.0
        with:
          tags: localbuild/${{ env.APP_DIR }}:latest
          push: false
          load: true
          context: "${{ env.APP_DIR}}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/${{ env.APP_DIR}}:latest"